config/routes.rb
Rails.application.routes.draw do

  # scope "map" do
    get 'map' => 'map#index'
    post 'map' => 'map#index'
  # end

  get 'mission' => 'map#show'
  
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }
  devise_scope :user do
    get 'users/sign_up', to: 'users/registrations#new'
    get 'users/sign_in', to: 'users/sessions#new'
    delete 'users/sign_out', to: 'users/sessions#destroy'
  end 

  devise_scope :user do
    root to: 'home#index'
  end 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
	require 'net/http'
  require 'json'
  def azavea_api_response
    # encode URI using the URI constant
    uri1 = URI("https://raw.githubusercontent.com/azavea/geo-data/master/Neighborhoods_Philadelphia/Neighborhoods_Philadelphia.geojson")
    p uri1
    # tell Net::HTTP to GET the URI
    # @response = JSON.parse(Net::HTTP.get(uri))
    @nei_response = Net::HTTP.get(uri1)
  end

  def counseling_api_response
# encode URI using the URI constant
    uri2 = URI("https://raw.githubusercontent.com/azavea/geo-data/master/Neighborhoods_Philadelphia/Neighborhoods_Philadelphia.geojson")
    p uri2
    # tell Net::HTTP to GET the URI
    # @response = JSON.parse(Net::HTTP.get(uri))
    @counsel_response = Net::HTTP.get(uri2)
end
    def parks_api_response
      uri3 = URI("http://data.phl.opendata.arcgis.com/datasets/4df9250e3d624ea090718e56a9018694_0.geojson")
      p uri3
      @parks_response = Net::HTTP.get(uri3)
    end
    def affordable_api_response
# encode URI using the URI constant
  uri2 = URI("https://phl.carto.com/api/v2/sql?q=SELECT+*+FROM+affordablehousingproduction&filename=affordablehousingproduction&format=geojson&skipfields=cartodb_id")
  p uri2
  # tell Net::HTTP to GET the URI
  # @response = JSON.parse(Net::HTTP.get(uri))
  @affordable_response = Net::HTTP.get(uri2)
end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index 
    end
end

app/controllers/map_controller.rb
class MapController < ApplicationController

  

  def index
    if params[:address].present?
      @string = "#{params[:address]}"
    else
      @string = "2810 Jasper St"
    end
    @zillow = Rubillow::PropertyDetails.deep_search_results({ :address => @string, :citystatezip => 'Philadelphia, PA' })
    # @realprop = Rubillow::PropertyDetails.deep_search_results({ :address => '2801 Jasper St', :citystatezip => 'Philadelphia, PA' })
    @hood = Rubillow::Neighborhood.demographics({ :state => 'PA', :city => 'Philadelphia', :neighborhood => @zillow.region })
    @comps = Rubillow::PropertyDetails.deep_comps({ :zpid => @zillow.zpid, :count => 4 })
  end

  def show
  	
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
    def results
        # @realprop = Rubillow::PropertyDetails.deep_search_results({ :address => '2801 Jasper St', :citystatezip => 'Philadelphia, PA' })
        # @hood = Rubillow::Neighborhood.demographics({ :state => 'PA', :city => 'Philadelphia', :neighborhood => @realprop.region })
        # @comps = Rubillow::PropertyDetails.deep_comps({ :zpid => @realprop.zpid, :count => 4 })
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  def new
    super
  end

  # POST /resource/confirmation
  def create
    super
  end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    super
  end

  # protected

  # The path used after resending confirmation instructions.
  def after_resending_confirmation_instructions_path_for(resource_name)
    new_user_confirmation_path
  end

  # The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    signin_path
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  def new
    super
  end

  # POST /resource/password
  def create
    super
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    super
  end

  # PUT /resource/password
  def update
    super
  end

  protected

  def after_resetting_password_path_for(resource)
    root_path
  end

  # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(resource_name)
    signin_path
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    # redirect_to map_index_path
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/home/index.html.erb
<div class="landing">
  <h1 class="cover-text"><span class="logo-small">Welcome to</span> | <span class="logo-big">Philly Grid</span></h1>
  <p class="cover-text cover-text-p">Looking for an apartment? Join our vibrant community of Philadelphians planning their next move.<br /> In the city of neighborhoods & brotherly love, there's something for everybody.</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Philly Grid</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.0/normalize.css" />
    <link href="https://fonts.googleapis.com/css?family=PT+Serif|Roboto:300" rel="stylesheet">
    <script src="https://openlayers.org/en/v4.6.5/build/ol.js" type="text/javascript"></script>
    <!-- OpenLayers is a mapping service that doesn't require
    OAuth Authentication or app registration and is compatible
    with Mapstraction -->
    <link rel="stylesheet" href="https://openlayers.org/en/v4.6.5/css/ol.css" type="text/css">
    <!-- leaflet CDN for using the library and importing GeoJSON -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css" />
    <!-- leaflet also recommends using these for extra security purposes -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css" integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ==" crossorigin="" />
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"></script>
    <script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js" integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw==" crossorigin=""></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag params[:controller] %>
  </head>

  <body>
    <div id="body-grid">
      <div class="header">
        <nav class="nav">
          <ul class="nav-list">
            <li><a><%= link_to 'Home', root_path %></a></li>
            <li><a href="#"><%= link_to 'Mission', mission_path %> </a></li>
            <li><a href="#"> <%= link_to 'Map', map_path %></a></li>
            <%# <li><a><%= link_to 'Sign In', new_user_session_path</a></li>  %>
              <%# <% if user_signed_in? %>
                <%# <li><a><%= link_to 'Sign Out', destroy_user_session_path, method: :delete</a></li>  %>
              <%# <% else %> 
              <%# <% end %> 
          </ul>
        </nav>
      </div>

    <section class="main-background">
      <div class="yield-content">
        <%= yield %>
          <div>
            <p class="notice"><%= notice %></p>
            <p class="alert"><%= alert %></p>
          </div>
      </div>
    </section>

    <div class="footer">
      <ul class="footer-list">
        <li> &copy 2018 <strong>Philly Grid</strong> </li>
        <li><a href="#"> Terms </a></li>
        <li><a href="#"> Privacy </a></li>
      </ul>
      <ul class="footer-list3">
          <li><a href="https://beta.phila.gov/" target="_blank"> <%= image_tag("city-of-philadelphia.png", class: "thanks-icons") %> </a></li>
          <li><a href="https://www.azavea.com/" target="_blank"> <%= image_tag("azavea-logo-white.png", class: "thanks-icons", style: "margin-bottom: 7%") %> </a></li>
          <li><a href="https://www.opendataphilly.org/" target="_blank"> <%= image_tag("odp-logo.png", class: "thanks-icons", style: "width: 185px") %> </a></li>
      </ul>
    </div>
  </div>
  </body>
</html>

app/views/map/index.html.erb
<h2 class="browse">Browse Neighborhoods & Available Apartments</h2>

  <!-- Checkboxes to toggle map layers on/off -->

<div id="grid">
  <main id="map" class="map main">
    <div class="checkboxes">
      <input type="checkbox" id="checkbox_Nej" checked>  Neighborhoods
      <input type="checkbox" id="checkbox" checked>  Affordable Housing
      <input type="checkbox" id="checkbox_counsel" checked>  Commercial Corridors
      <input type="checkbox" id="checkbox_parks" checked> Parking Permits
    </div>

    <%= javascript_include_tag "map", "data-turbolinks-track" => true  %>

    <style>
      .ol-viewport {
        height: 96.3% !important;
        position: sticky !important;
      }
    </style>
  </main>

<!-- Aside for displaying instructions and info for selected elements on map -->

  <aside class="panel">
    <div class="row">
      <p> <span><h3>Philly Grid |</h3></span> is a web app designed to help you research homes and their surrounding areas within the City of Philadelphia. Use the checkboxes above the map to toggle layers like Neighborhood Boundaries, Affordable Housing, Commercial Corridors and Parking. Hover over the map to view neighborhood names.  Click on any map element to view more detail.
    </div>
    <div class="row-2">
      <h3> At a Glance... </h3>
        <p id="info"> </p>
        <p> <form class="form-inline" style="display:none">
          <select id="type" class="form-control">
            <option value="click" selected>Inspect a neighborhood</option>
          </select>
          </form></p>
          <p id="description" style="display:none"> <b>Selection Description: </b><br>
          <div id="Neighborhood_Info" style="display:none"></div></p>
          <p><div id="counsel_info"></div><div id="afford_info"></div><div id="res_parking_info"></div></p>
    </div>
  </aside>

    <!-- form is supposed to pass params of "location" to the UJS function -->
<div class="row-3">
  <div class="results">
    <% if @string == "2810 Jasper St" %>
    <h1>Enter a street address to view search results below =></h1>
    <% else %>
    <h1>Here's what we found...</h1>
    <% end %>
    <div class="search">
      <div class="input">
        <p>Search for an Address:</p>
        <%# <form data-remote="true" action="/map/index" data-method="post"></form> %>
        <%# <input id="searchField" name="address" type="text" placeholder="1601 Cherry Street"> %>
        <%# <button id="searchButton" type="submit" value="Submit">Submit</button> %>
          <%= form_tag("/map", method: "get", id: "main") do %>
            <%= text_field_tag(:address, @string) %>
            <%= submit_tag("Submit", id: "submit") %>
          <% end %>
      </div>
    </div>
  
  <% if @string == "2810 Jasper St" %>
  </div>
  <% else %>
    <div class="property-data">
      <% if @zillow.success? %>
      <h6><%= @zillow.address[:street] %>, <%= @zillow.address[:city] %>, <%= @zillow.address[:state] %> <%= @zillow.address[:zipcode] %></h6>
      <p> <%= @zillow.use_code %> built in <%= @zillow.year_built %></p>
      <p> <%= @zillow.bathrooms.to_i %> bathrooms </p>
      <p> <%= @zillow.bedrooms.to_i %> bedrooms </p>
      <p> <%= @zillow.total_rooms.to_i %> total rooms </p>	
      <p> <%= @zillow.finished_square_feet %> sq. ft of finished space on <%= @zillow.lot_size_square_feet %> sq. ft lot</p>
      <p>Tax-assessed market value at <%= number_to_currency(@zillow.tax_assessment) %> in <%= @zillow.tax_assessment_year %> </p>

      <h6>Zillow Home Valuation Estimate:</h6>
      <p> Low: <%= number_to_currency(@zillow.valuation_range[:low]) %> </p>
      <p> Med: <%= number_to_currency(@zillow.price) %> </p>
      <p> High: <%= number_to_currency(@zillow.valuation_range[:high]) %> </p>

      <h6>Zillow Rent Estimate: </h6>
      <% else %>
      <% end %>
    </div>
  
  


    <div class="hood-data">
	    <h6> Richmond Neighborhood Demographics: </h6>
      <% if @hood.segmentation.present? %>
	      <% @hood.segmentation.each do | name, value | %>
	        <p><em> <%= name %> </em><br>
	          <%= value.map{| _k,v | "#{v}\n"}.join("\n") %> </p>
	      <% end %>
	        <p style="white-space:pre-wrap"><em>Education Level </em><br><%= @hood.characteristics['Education'].join("\n") %> </p>
	        <p style="white-space:pre-wrap"><em>Employment </em><br><%= @hood.characteristics['Employment'].join("\n") %> </p>
	        <p style="white-space:pre-wrap"><em>Income </em><br><%= @hood.characteristics['Income'].join("\n") %> </p>
	        <p style="white-space:pre-wrap"><em>People & Culture </em><br><%= @hood.characteristics['People & Culture'].join("\n")%> </p>
      <% else %>
      <p>Sorry, Zillow has no demographic information for this neighborhood.</p>
      <% end %>
    </div>
  
  

    <div class="comp-data">
	    <h6>Comparable Homes in the Area: </h6>
	    <% if @comps.success? %>
	      <% @comps.comparables.each do | score, comp | %>
	        <p><em><%= comp.address[:street] %> </em><br>     
            Zillow Comparability Score: <%= score %><br>
            Last Sold Date: <%= comp.last_sold_date %><br>
		        Last Sale Price: <%= number_to_currency(comp.last_sold_price) %> </p>
		    <% end %> 
	    <% else %>
	      <p>Sorry, Zillow has no comparable home data available for this address</p>
      <% end %>
    </div>
  </div>
  <% end %>
  </div>
</div>

app/views/map/show.html.erb
	
<%# <section class="main-background">	 %>
	<div id="mission-page" class="landing">
		<div class="mission">
			<p>Philly Grid was conceived as an apartment search web application that could enable users to obtain detailed information about the neighborhood surrounding their prospective home. In one week, our team learned to use the OpenLayers JavaScript library to work with five different APIs, and we built a multi-layered map interface. Users can toggle each layer to view the boundaries of any neighborhood in Philly, along with the distributions of three resources relevant to apartment shoppers: affordable housing, housing counseling, and parks throughout the city.</p>

			<p>Users can also click to select an individual element from any layer and view details from its API such as the name and full address of an organization.
			</p>
		</div>
	</div>
<%# </section> %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>